name: frappe_dart
description: A comprehensive Dart wrapper for interacting with the Frappe API, providing easy access to its features and enabling seamless communication with Frappe-based systems.
version: 0.0.6
homepage: https://github.com/kinetsystems/frappe_dart
repository: https://github.com/kinetsystems/frappe_dart
issue_tracker: https://github.com/kinetsystems/frappe_dart/issues
topics:
  - frappe
  - api
  - dart

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  dio: ^5.9.2
  equatable: ^2.0.8
  socket_io_client: ^3.1.4

dev_dependencies:
  build_runner: ^2.13.1
  mockito: ^5.6.4
  test: ^1.31.0
  very_good_analysis: ^10.2.0
